### PR TITLE
 Make the code compile to wasm again, and add CI check for it

### LINKED ISSUE #73: Wasm bindings are broken on `main`
I do not know to what extent you care about/want to maintain the wasm bindings. But currently they are broken. Running `deno task build` on `main` now produce a lot of errors due to refactorings in the library and code behind `#[cfg(target_arch = "wasm32")]` not being checked by us or the CI.

If we want to keep wasm bindings in the library, then I suggest adding a CI step to automatically verify that `wasm-pack build --target web` runs with an exit code of zero :)

I have never used this library via wasm before. But I had a refactoring in mind that I was curious if javascript could handle at all, so I wanted to get familiar with the wasm bindings.

### PR DESCRIPTION
**Pull request by faern**
Fixes #73

### CODE REVIEW

File: src/spectrum.rs [hunk 1]
```diff
@@ -302,17 +302,6 @@ impl Spectrum {
...
-
-    /// Calculates the Color Rendering Index values for illuminant spectrum.
-    ///
-    /// To use this function, first use `await CRI.init()`, which downloads the
-    /// Test Color Samples required for the calculation.  These are downloaded
-    /// seperately to limit the size of the main web assembly library.
-    #[cfg(feature = "cri")]
-    #[wasm_bindgen(js_name=cri)]
-    pub fn cri_js(&self) -> Result<crate::cri::CRI, Error> {
-        todo!()
```
Comment (faern) [inline src/spectrum.rs:314]: Since CRI is a property of an illuminant, and not just any spectrum, I figured it's enough to have the method on `Illuminant` and not also on `Spectrum`.

File: src/illuminant.rs [hunk 2]
```diff
@@ -314,16 +314,16 @@ impl Illuminant {
     /// which takes a wavelength domain and spectral data as arguments.
```
Comment (faern) [inline src/illuminant.rs:314]: This documentation seems highly outdated? Talking about categories and stuff that the method does not actually deal with. I only fixed the issues in the code and left the documentation for now, since you probably knows better how to fix it.

File: src/illuminant.rs [hunk 3]
```diff
@@ -333,8 +333,8 @@ impl Illuminant {
     /// seperately to limit the size of the main web assembly library.
```
Comment (faern) [inline src/illuminant.rs:333]: Is this documentation outdated, or am I not understanding how these wasm bindings work? Where is it downloading extra color patch data? I think this part of the docs should be removed?
